<?php
// module/Attendance/view/attendance/attendance/delete.phtml:

$title = 'Delete Attendance';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete - 
    Punch-In: '<?php echo $this->escapeHtml($attendance->punch_in); ?>' till 
    Punch out: '<?php echo $this->escapeHtml($attendance->punch_out); ?>'?
</p>
<?php
$url = $this->url('attendance', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $attendance->id; ?>" />
    <input type="submit" class="btn btn-success" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>